fwd: SG_data/DTG-SG-188_R1_001.fastq.gz
rev: SG_data/DTG-SG-188_R2_001.fastq.gz

assembly: 
  HiC_assembly/Mgal6.fa

DATADIR:
  /lustre/backup/WUR/ABGC/shared/ABGC_Projects/Turkey_Assembly/

BAM_prefix: DTG-SG-188