# Reads dir
READS_DIR: SG_data/

# Reference
assembly: HiC_assembly/Mgal6.fa

# Directory with data to use (for reads and reference)
DATADIR: /lustre/backup/WUR/ABGC/shared/ABGC_Projects/Turkey_Assembly/

# prefix for the results
my_prefix: DTG-SG-188